// freebridgefe/src/contracts/signature-pad-modal.tsx
import React, { useRef, useEffect, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Eraser, Check, PenTool } from 'lucide-react';

interface SignaturePadModalProps {
  onSign: (signatureDataUrl: string) => void;
  onClose: () => void;
  signerName: string;
}

export function SignaturePadModal({ onSign, onClose, signerName }: SignaturePadModalProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isDrawing, setIsDrawing] = useState(false);
  const [hasDrawn, setHasDrawn] = useState(false);

  const getCanvasContext = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return null;
    return canvas.getContext('2d');
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    // Set canvas resolution for sharp rendering
    const rect = canvas.getBoundingClientRect();
    const dpr = window.devicePixelRatio || 1;
    canvas.width = rect.width * dpr;
    canvas.height = rect.height * dpr;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    ctx.scale(dpr, dpr);
    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';
    ctx.lineWidth = 2.5;
    ctx.strokeStyle = '#ffffff';
  }, []);

  const getPosition = (e: React.MouseEvent | React.TouchEvent) => {
    const canvas = canvasRef.current;
    if (!canvas) return { x: 0, y: 0 };
    const rect = canvas.getBoundingClientRect();

    if ('touches' in e) {
      return {
        x: e.touches[0].clientX - rect.left,
        y: e.touches[0].clientY - rect.top,
      };
    }
    return {
      x: e.clientX - rect.left,
      y: e.clientY - rect.top,
    };
  };

  const startDrawing = (e: React.MouseEvent | React.TouchEvent) => {
    e.preventDefault();
    const ctx = getCanvasContext();
    if (!ctx) return;
    const pos = getPosition(e);
    ctx.beginPath();
    ctx.moveTo(pos.x, pos.y);
    setIsDrawing(true);
    setHasDrawn(true);
  };

  const draw = (e: React.MouseEvent | React.TouchEvent) => {
    e.preventDefault();
    if (!isDrawing) return;
    const ctx = getCanvasContext();
    if (!ctx) return;
    const pos = getPosition(e);
    ctx.lineTo(pos.x, pos.y);
    ctx.stroke();
  };

  const stopDrawing = (e: React.MouseEvent | React.TouchEvent) => {
    e.preventDefault();
    setIsDrawing(false);
  };

  const clearCanvas = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    const dpr = window.devicePixelRatio || 1;
    ctx.clearRect(0, 0, canvas.width / dpr, canvas.height / dpr);
    setHasDrawn(false);
  };

  const handleConfirm = () => {
    const canvas = canvasRef.current;
    if (!canvas || !hasDrawn) return;
    const dataUrl = canvas.toDataURL('image/png');
    onSign(dataUrl);
  };

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 backdrop-blur-sm p-4"
        onClick={(e) => e.target === e.currentTarget && onClose()}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          transition={{ type: 'spring', duration: 0.5 }}
          className="w-full max-w-lg bg-gray-900 rounded-3xl border border-white/10 overflow-hidden shadow-2xl"
        >
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-white/10">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center">
                <PenTool className="w-5 h-5 text-white" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white">전자 서명</h3>
                <p className="text-sm text-white/60">서명자: {signerName}</p>
              </div>
            </div>
            <motion.button
              onClick={onClose}
              className="p-2 hover:bg-white/10 rounded-full transition-colors"
              whileHover={{ scale: 1.1, rotate: 90 }}
              whileTap={{ scale: 0.9 }}
            >
              <X className="w-5 h-5 text-white/60" />
            </motion.button>
          </div>

          {/* Canvas Area */}
          <div className="p-6">
            <div className="text-sm text-white/40 mb-3">아래 영역에 서명해주세요</div>
            <div className="relative rounded-2xl border-2 border-dashed border-white/20 bg-white/5 overflow-hidden">
              <canvas
                ref={canvasRef}
                className="w-full cursor-crosshair touch-none"
                style={{ height: '200px' }}
                onMouseDown={startDrawing}
                onMouseMove={draw}
                onMouseUp={stopDrawing}
                onMouseLeave={stopDrawing}
                onTouchStart={startDrawing}
                onTouchMove={draw}
                onTouchEnd={stopDrawing}
              />
              {!hasDrawn && (
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                  <p className="text-white/20 text-lg font-medium">여기에 서명하세요</p>
                </div>
              )}
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-3 p-6 pt-0">
            <motion.button
              onClick={clearCanvas}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-white/80 font-medium transition-colors"
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <Eraser className="w-4 h-4" />
              지우기
            </motion.button>
            <motion.button
              onClick={handleConfirm}
              disabled={!hasDrawn}
              className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl font-semibold transition-all ${
                hasDrawn
                  ? 'bg-gradient-to-r from-blue-500 to-cyan-500 text-white shadow-lg'
                  : 'bg-white/5 text-white/30 cursor-not-allowed'
              }`}
              whileHover={hasDrawn ? { scale: 1.02 } : {}}
              whileTap={hasDrawn ? { scale: 0.98 } : {}}
            >
              <Check className="w-4 h-4" />
              서명 확인
            </motion.button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

// freebridgefe/src/views/employer/Contracts/components/SignaturePadModal.vue
<script setup lang="ts">
import { ref } from 'vue';
import { X, Eraser, Check, PenTool } from 'lucide-vue-next';
import { useSignaturePad } from '@/composables/useSignaturePad';

const props = defineProps<{
    signerName: string;
}>();

const emit = defineEmits<{
    (e: 'sign', dataUrl: string): void;
    (e: 'close'): void;
}>();

const canvasRef = ref<HTMLCanvasElement | null>(null);
const { isEmpty, clear, toDataURL } = useSignaturePad(canvasRef, {
    penColor: '#ffffff',
    minWidth: 0.5,
    maxWidth: 2.5,
});

const handleConfirm = () => {
    if (isEmpty.value) return;
    const dataUrl = toDataURL('image/png');
    emit('sign', dataUrl);
};

const handleBackdropClick = (e: MouseEvent) => {
    if (e.target === e.currentTarget) {
        emit('close');
    }
};
</script>

<template>
    <div
        class="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 backdrop-blur-sm p-4"
        @click="handleBackdropClick"
    >
        <div
            class="w-full max-w-lg bg-gray-900 rounded-3xl border border-white/10 overflow-hidden shadow-2xl"
            v-motion
            :initial="{ opacity: 0, scale: 0.95, y: 20 }"
            :enter="{ opacity: 1, scale: 1, y: 0, transition: { type: 'spring', duration: 500 } }"
            :leave="{ opacity: 0, scale: 0.95, y: 20 }"
        >
            <!-- Header -->
            <div class="flex items-center justify-between p-6 border-b border-white/10">
                <div class="flex items-center gap-3">
                    <div
                        class="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center"
                    >
                        <PenTool class="w-5 h-5 text-white" />
                    </div>
                    <div>
                        <h3 class="text-lg font-bold text-white">전자 서명</h3>
                        <p class="text-sm text-white/60">서명자: {{ signerName }}</p>
                    </div>
                </div>
                <button
                    @click="$emit('close')"
                    class="p-2 hover:bg-white/10 rounded-full transition-colors"
                    v-motion
                    :hover="{ scale: 1.1, rotate: 90 }"
                    :tap="{ scale: 0.9 }"
                >
                    <X class="w-5 h-5 text-white/60" />
                </button>
            </div>

            <!-- Canvas Area -->
            <div class="p-6">
                <div class="text-sm text-white/40 mb-3">아래 영역에 서명해주세요</div>
                <div
                    class="relative rounded-2xl border-2 border-dashed border-white/20 bg-white/5 overflow-hidden"
                >
                    <canvas
                        ref="canvasRef"
                        class="w-full cursor-crosshair touch-none"
                        style="height: 200px"
                    />
                    <div
                        v-if="isEmpty"
                        class="absolute inset-0 flex items-center justify-center pointer-events-none"
                    >
                        <p class="text-white/20 text-lg font-medium">여기에 서명하세요</p>
                    </div>
                </div>
            </div>

            <!-- Actions -->
            <div class="flex items-center gap-3 p-6 pt-0">
                <button
                    @click="clear"
                    class="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-white/80 font-medium transition-colors"
                    v-motion
                    :hover="{ scale: 1.02 }"
                    :tap="{ scale: 0.98 }"
                >
                    <Eraser class="w-4 h-4" />
                    지우기
                </button>
                <button
                    @click="handleConfirm"
                    :disabled="isEmpty"
                    class="flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl font-semibold transition-all"
                    :class="
                        isEmpty
                            ? 'bg-white/5 text-white/30 cursor-not-allowed'
                            : 'bg-gradient-to-r from-blue-500 to-cyan-500 text-white shadow-lg'
                    "
                    v-motion
                    :hover="isEmpty ? {} : { scale: 1.02 }"
                    :tap="isEmpty ? {} : { scale: 0.98 }"
                >
                    <Check class="w-4 h-4" />
                    서명 확인
                </button>
            </div>
        </div>
    </div>
</template>
