// freebridgefe/src/settlement/settlement-detail-modal.tsx
import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, DollarSign, CheckCircle, Clock } from 'lucide-react';
import { Settlement } from '@/types/contract';

interface SettlementDetailModalProps {
  settlement: Settlement;
  onClose: () => void;
}

// 결제 단계 타임라인
const paymentStages = [
  { id: 1, label: '정산 요청', status: 'PENDING' },
  { id: 2, label: '검토중', status: 'PROCESSING' },
  { id: 3, label: '승인 완료', status: 'APPROVED' },
  { id: 4, label: '지급 완료', status: 'PAID' },
];

export function SettlementDetailModal({ settlement, onClose }: SettlementDetailModalProps) {
  // 현재 단계 찾기
  const currentStageIndex = paymentStages.findIndex((s) => s.status === settlement.status);
  
  // 수수료율 계산 (역산)
  const feeRate = ((settlement.platformFee / settlement.totalAmount) * 100).toFixed(1);

  return (
    <AnimatePresence>
      <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="bg-gray-900/95 backdrop-blur-xl border border-white/10 rounded-3xl max-w-3xl w-full max-h-[90vh] overflow-y-auto shadow-2xl"
        >
          <div className="sticky top-0 bg-gradient-to-br from-gray-800/95 to-gray-900/95 backdrop-blur-xl border-b border-white/10 p-6 flex items-center justify-between z-10">
            <h2 className="text-2xl font-bold text-white">정산 상세 내역</h2>
            <motion.button
              whileHover={{ scale: 1.1, rotate: 90 }}
              whileTap={{ scale: 0.9 }}
              onClick={onClose}
              className="p-2 hover:bg-white/10 rounded-xl transition-colors"
            >
              <X className="w-6 h-6 text-white" />
            </motion.button>
          </div>

          <div className="p-6 space-y-6">
            {/* 프로젝트 정보 */}
            <div className="bg-gradient-to-br from-blue-500/20 to-purple-500/20 backdrop-blur-xl border border-blue-400/30 rounded-2xl p-6 shadow-lg">
              <div className="text-sm text-white/60 mb-1">프로젝트</div>
              <div className="text-2xl font-medium text-white mb-2">{settlement.projectName}</div>
              <div className="text-white/70">{settlement.employerName}</div>
            </div>

            {/* 타임라인 스테퍼 */}
            <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-lg">
              <h3 className="text-lg font-bold text-white mb-6">정산 진행 상태</h3>
              <div className="relative">
                {/* 프로그레스 라인 */}
                <div className="absolute top-6 left-6 right-6 h-1 bg-white/10">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{
                      width: `${(currentStageIndex / (paymentStages.length - 1)) * 100}%`,
                    }}
                    transition={{ duration: 1, ease: 'easeOut' }}
                    className="h-full bg-gradient-to-r from-blue-500 via-purple-500 to-green-500"
                  />
                </div>

                {/* 단계 */}
                <div className="relative flex justify-between">
                  {paymentStages.map((stage, index) => {
                    const isCompleted = index <= currentStageIndex;
                    const isCurrent = index === currentStageIndex;

                    return (
                      <div key={stage.id} className="flex flex-col items-center">
                        <motion.div
                          initial={{ scale: 0 }}
                          animate={{ scale: 1 }}
                          transition={{ delay: 0.2 + index * 0.1 }}
                          className={`w-12 h-12 rounded-full border-4 flex items-center justify-center transition-all ${
                            isCompleted
                              ? 'bg-gradient-to-br from-blue-500 to-green-500 border-white/20 shadow-lg'
                              : 'bg-gray-800 border-white/10'
                          }`}
                        >
                          {isCompleted ? (
                            <CheckCircle className="w-6 h-6 text-white" />
                          ) : (
                            <div className="w-3 h-3 rounded-full bg-white/30" />
                          )}
                        </motion.div>
                        <div
                          className={`mt-3 text-sm text-center ${
                            isCurrent ? 'font-medium text-blue-400' : 'text-white/60'
                          }`}
                        >
                          {stage.label}
                        </div>
                        {isCurrent && (
                          <div className="mt-1 px-2 py-0.5 bg-blue-500/20 text-blue-300 text-xs rounded-full border border-blue-500/30">
                            진행중
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* 금액 breakdown */}
            <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-lg">
              <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                <DollarSign className="w-5 h-5 text-green-400" />
                금액 상세
              </h3>

              <div className="space-y-4">
                <div className="flex items-center justify-between pb-4 border-b border-white/10">
                  <span className="text-white/60">총 정산 금액</span>
                  <span className="text-2xl font-medium text-white">
                    {settlement.totalAmount.toLocaleString()}원
                  </span>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center justify-between text-red-400">
                    <span>플랫폼 수수료 ({feeRate}%)</span>
                    <span>- {settlement.platformFee.toLocaleString()}원</span>
                  </div>
                  <div className="flex items-center justify-between text-red-400">
                    <span>원천세 (10%)</span>
                    <span>- {settlement.tax.toLocaleString()}원</span>
                  </div>
                </div>

                <div className="pt-4 border-t border-white/10 flex items-center justify-between">
                  <span className="text-lg font-medium text-white">실수령액</span>
                  <span className="text-3xl font-bold text-green-400">
                    {settlement.netAmount.toLocaleString()}원
                  </span>
                </div>
              </div>
            </div>

            {/* 계좌 정보 */}
            {settlement.bankAccount && (
              <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-lg">
                <h3 className="text-lg font-bold text-white mb-3">입금 계좌</h3>
                <div className="text-xl font-medium text-white">{settlement.bankAccount}</div>
              </div>
            )}

            {/* 날짜 정보 */}
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-4">
                <div className="flex items-center gap-2 text-white/60 mb-2">
                  <Clock className="w-4 h-4" />
                  <span className="text-sm">요청일</span>
                </div>
                <div className="font-medium text-white">
                  {new Date(settlement.requestDate).toLocaleDateString('ko-KR')}
                </div>
              </div>

              {settlement.paidDate && (
                <div className="bg-green-500/20 border border-green-400/30 rounded-2xl p-4">
                  <div className="flex items-center gap-2 text-green-300 mb-2">
                    <CheckCircle className="w-4 h-4" />
                    <span className="text-sm">지급일</span>
                  </div>
                  <div className="font-medium text-green-200">
                    {new Date(settlement.paidDate).toLocaleDateString('ko-KR')}
                  </div>
                </div>
              )}
            </div>

            {/* 상태별 안내 메시지 */}
            {settlement.status === 'PROCESSING' && (
              <div className="bg-blue-500/20 border border-blue-400/30 rounded-2xl p-4">
                <div className="text-sm text-blue-200">
                  💡 정산이 처리 중입니다. 영업일 기준 2-3일 내 승인 예정입니다.
                </div>
              </div>
            )}

            {settlement.status === 'APPROVED' && (
              <div className="bg-purple-500/20 border border-purple-400/30 rounded-2xl p-4">
                <div className="text-sm text-purple-200">
                  ✅ 정산이 승인되었습니다. 곧 입금 처리될 예정입니다.
                </div>
              </div>
            )}

            {settlement.status === 'PAID' && (
              <div className="bg-green-500/20 border border-green-400/30 rounded-2xl p-4">
                <div className="text-sm text-green-200">
                  🎉 정산이 완료되어 입금되었습니다. 계좌를 확인해주세요.
                </div>
              </div>
            )}

            {/* 닫기 버튼 */}
            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={onClose}
              className="w-full py-4 bg-gradient-to-r from-blue-500 to-purple-500 text-white font-semibold rounded-2xl hover:shadow-xl transition-all"
            >
              닫기
            </motion.button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}

// freebridgefe/src/views/employer/Settlements/components/SettlementDetailModal.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
    X,
    DollarSign,
    CheckCircle,
    Clock,
    Send,
    Calendar,
    User,
    FileText,
    Download,
    Briefcase,
} from 'lucide-vue-next';

interface EmployerSettlement {
    id: string;
    contractId: string;
    billingAmount: number;
    platformFee: number;
    tax: number;
    totalAmount: number;
    installmentNumber: number;
    status: 'ISSUED' | 'PAID' | 'DISBURSED';
    invoicePdfUrl: string;
    projectName: string;
    freelancerName: string;
    freelancerId: string;
    employerId: string;
    dueDate: Date | string;
    paidDate?: Date | string;
}

const props = defineProps<{
    settlement: EmployerSettlement;
}>();

const emit = defineEmits<{
    (e: 'close'): void;
    (e: 'download', settlement: EmployerSettlement): void;
}>();

const statusConfig: Record<string, { label: string; icon: typeof CheckCircle; color: string; bg: string }> = {
    ISSUED: { label: '청구됨', icon: Clock, color: 'text-yellow-400', bg: 'bg-yellow-400/10 border-yellow-400/30' },
    PAID: { label: '결제 완료', icon: CheckCircle, color: 'text-blue-400', bg: 'bg-blue-400/10 border-blue-400/30' },
    DISBURSED: { label: '지급 완료', icon: Send, color: 'text-green-400', bg: 'bg-green-400/10 border-green-400/30' },
};

const paymentStages = [
    { id: 1, label: '청구서 발행', status: 'ISSUED' },
    { id: 2, label: '결제 완료', status: 'PAID' },
    { id: 3, label: '지급 완료', status: 'DISBURSED' },
];

const currentStageIndex = computed(() => {
    const statusOrder = ['ISSUED', 'PAID', 'DISBURSED'];
    return statusOrder.indexOf(props.settlement.status);
});

const formatDate = (date: Date | string) => {
    return new Date(date).toLocaleDateString('ko-KR', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
};

const formatCurrency = (amount: number) => {
    return amount.toLocaleString() + '원';
};

const handleDownload = () => {
    emit('download', props.settlement);
};
</script>

<template>
    <div class="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 p-4 font-sans text-white">
        <div
            class="bg-gray-900/95 backdrop-blur-xl border border-white/10 rounded-3xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl"
            v-motion
            :initial="{ opacity: 0, scale: 0.95, y: 20 }"
            :enter="{ opacity: 1, scale: 1, y: 0 }"
            :leave="{ opacity: 0, scale: 0.95, y: 20 }"
        >
            <!-- Header -->
            <div class="sticky top-0 bg-gray-900/95 backdrop-blur-xl border-b border-white/10 p-6 flex items-center justify-between z-10">
                <h2 class="text-2xl font-bold text-white">정산 상세 내역</h2>
                <button
                    @click="$emit('close')"
                    class="p-2 hover:bg-white/10 rounded-xl transition-colors"
                    v-motion
                    :hover="{ scale: 1.1, rotate: 90 }"
                    :tap="{ scale: 0.9 }"
                >
                    <X class="w-6 h-6 text-white" />
                </button>
            </div>

            <div class="p-6 space-y-6">
                <!-- Project Info Card -->
                <div class="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-lg">
                    <div class="flex items-start justify-between">
                        <div>
                            <div class="text-sm text-white/60 mb-1">프로젝트</div>
                            <div class="text-2xl font-bold text-white mb-2">{{ settlement.projectName }}</div>
                            <div class="flex items-center gap-2 text-white/70">
                                <User class="w-4 h-4" />
                                {{ settlement.freelancerName }}
                            </div>
                        </div>
                        <div
                            class="px-4 py-2 rounded-full border font-medium"
                            :class="statusConfig[settlement.status].bg"
                        >
                            <span :class="statusConfig[settlement.status].color">
                                {{ statusConfig[settlement.status].label }}
                            </span>
                        </div>
                    </div>
                </div>

                <!-- Progress Timeline -->
                <div class="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-lg">
                    <h3 class="text-lg font-bold text-white mb-6">정산 진행 상태</h3>
                    <div class="relative">
                        <!-- Progress Line -->
                        <div class="absolute top-6 left-6 right-6 h-1 bg-white/10">
                            <div
                                class="h-full bg-blue-500 transition-all duration-1000 ease-out"
                                :style="{ width: `${(currentStageIndex / (paymentStages.length - 1)) * 100}%` }"
                            ></div>
                        </div>

                        <!-- Stages -->
                        <div class="relative flex justify-between">
                            <div
                                v-for="(stage, index) in paymentStages"
                                :key="stage.id"
                                class="flex flex-col items-center"
                            >
                                <div
                                    class="w-12 h-12 rounded-full border-4 flex items-center justify-center transition-all bg-gray-800"
                                    :class="{
                                        'bg-blue-500 border-white/20 shadow-lg': index <= currentStageIndex,
                                        'border-white/10': index > currentStageIndex,
                                    }"
                                    v-motion
                                    :initial="{ scale: 0 }"
                                    :enter="{ scale: 1, transition: { delay: 0.2 + index * 0.1 } }"
                                >
                                    <CheckCircle v-if="index <= currentStageIndex" class="w-6 h-6 text-white" />
                                    <div v-else class="w-3 h-3 rounded-full bg-white/30" />
                                </div>
                                <div
                                    class="mt-3 text-sm text-center"
                                    :class="index === currentStageIndex ? 'font-medium text-blue-400' : 'text-white/60'"
                                >
                                    {{ stage.label }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Settlement Details -->
                <div class="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-lg">
                    <h3 class="text-lg font-bold text-white mb-4 flex items-center gap-2">
                        <FileText class="w-5 h-5 text-blue-400" />
                        청구 정보
                    </h3>

                    <div class="space-y-4">
                        <div class="flex items-center justify-between py-3 border-b border-white/10">
                            <span class="text-white/60">청구 회차</span>
                            <span class="font-medium text-white">{{ settlement.installmentNumber }}차</span>
                        </div>
                        <div class="flex items-center justify-between py-3 border-b border-white/10">
                            <span class="text-white/60">청구 금액 (공급가액)</span>
                            <span class="text-xl font-bold text-white">{{ formatCurrency(settlement.billingAmount) }}</span>
                        </div>
                        <div class="flex items-center justify-between py-3 border-b border-white/10">
                            <span class="text-white/60">플랫폼 수수료 (5%)</span>
                            <span class="text-white">{{ formatCurrency(settlement.platformFee) }}</span>
                        </div>
                        <div class="flex items-center justify-between py-3 border-b border-white/10">
                            <span class="text-white/60">부가세 (10%)</span>
                            <span class="text-white">{{ formatCurrency(settlement.tax) }}</span>
                        </div>
                        <div class="flex items-center justify-between py-3 border-b border-white/10 bg-white/5 px-4 rounded-xl mt-2">
                            <span class="text-white font-medium">총 결제 금액</span>
                            <span class="text-2xl font-bold text-blue-400">{{ formatCurrency(settlement.totalAmount) }}</span>
                        </div>
                        <div class="flex items-center justify-between py-3 border-b border-white/10">
                            <span class="text-white/60">계약 ID</span>
                            <span class="font-medium text-white flex items-center gap-1">
                                {{ settlement.contractId }}
                                <Briefcase class="w-3 h-3" />
                            </span>
                        </div>
                    </div>
                </div>

                <!-- Dates -->
                <div class="grid md:grid-cols-2 gap-4">
                    <div class="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-4">
                        <div class="flex items-center gap-2 text-white/60 mb-2">
                            <Calendar class="w-4 h-4" />
                            <span class="text-sm">납부 기한</span>
                        </div>
                        <div class="font-medium text-white">
                            {{ formatDate(settlement.dueDate) }}
                        </div>
                    </div>

                    <div
                        v-if="settlement.paidDate"
                        class="bg-white/5 border border-white/10 rounded-2xl p-4"
                    >
                        <div class="flex items-center gap-2 text-white/60 mb-2">
                            <CheckCircle class="w-4 h-4" />
                            <span class="text-sm">결제일</span>
                        </div>
                        <div class="font-medium text-white">
                            {{ formatDate(settlement.paidDate) }}
                        </div>
                    </div>
                </div>

                <!-- Status Messages -->
                <div v-if="settlement.status === 'ISSUED'" class="bg-white/5 border border-white/10 rounded-2xl p-4">
                    <div class="text-sm text-white/80">
                        청구서가 발행되었습니다. 납부 기한 내에 결제를 완료해주세요.
                    </div>
                </div>

                <div v-if="settlement.status === 'PAID'" class="bg-white/5 border border-white/10 rounded-2xl p-4">
                    <div class="text-sm text-white/80">
                        결제가 완료되었습니다. 프리랜서에게 지급 처리 중입니다.
                    </div>
                </div>

                <div v-if="settlement.status === 'DISBURSED'" class="bg-white/5 border border-white/10 rounded-2xl p-4">
                    <div class="text-sm text-white/80">
                        프리랜서에게 정산이 완료되었습니다.
                    </div>
                </div>

                <!-- Action Buttons -->
                <div class="flex gap-3">
                    <button
                        @click="handleDownload"
                        class="flex-1 py-4 bg-white/5 border border-white/10 text-white font-semibold rounded-2xl hover:bg-white/10 transition-all flex items-center justify-center gap-2"
                        v-motion
                        :hover="{ scale: 1.02 }"
                        :tap="{ scale: 0.98 }"
                    >
                        <Download class="w-5 h-5" />
                        청구서 다운로드
                    </button>
                    <button
                        @click="$emit('close')"
                        class="flex-1 py-4 bg-white/5 border border-white/10 hover:bg-white/10 text-white font-semibold rounded-2xl transition-all"
                        v-motion
                        :hover="{ scale: 1.02 }"
                        :tap="{ scale: 0.98 }"
                    >
                        닫기
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>
